MINIMUM_AMOUNT_OF_LEGS = 0

MINIMUM_AMOUNT_OF_WINGS = 0

CLAWS_BOOST_OPTIONS = [1, 2, 3, 4]
TEETH_BOOST_OPTIONS = [0, 3, 6, 9]

NO_STAMINA = 0
MINIMUM_MAX_STAMINA = 200
MAXIMUM_MAX_STAMINA = 500

NO_HEALTH = 0
MINIMUM_MAX_HEALTH = 100
MAXIMUM_MAX_HEALTH = 200

MINIMUM_POWER = 8
MAXIMUM_POWER = 16

STATUS_PREY = 0
STATUS_PREDATOR = 1

STATUS_DESCRIPTIONS = {STATUS_PREY: "Prey", STATUS_PREDATOR: "Predator"}

CLAWS_DESCRIPTIONS = {
    CLAWS_BOOST_OPTIONS[0]: "No claws",
    CLAWS_BOOST_OPTIONS[1]: "Small claws",
    CLAWS_BOOST_OPTIONS[2]: "Medium claws",
    CLAWS_BOOST_OPTIONS[3]: "Big claws",
}

TEETH_DESCRIPTIONS = {
    TEETH_BOOST_OPTIONS[0]: "No teeth",
    TEETH_BOOST_OPTIONS[1]: "Dull teeth",
    TEETH_BOOST_OPTIONS[2]: "Average teeth",
    TEETH_BOOST_OPTIONS[3]: "Sharp teeth",
}
