STAMINA_TO_CRAWL = 0
STAMINA_TO_HOP = 20
STAMINA_TO_WALK = 40
STAMINA_TO_RUN = 60
STAMINA_TO_FLY = 80

STAMINA_USED_BY_CRAWL = 1
STAMINA_USED_BY_HOP = 2
STAMINA_USED_BY_WALK = 2
STAMINA_USED_BY_RUN = 4
STAMINA_USED_BY_FLY = 4

SPEED_CRAWL = 1
SPEED_HOP = 3
SPEED_WALK = 4
SPEED_RUN = 6
SPEED_FLY = 8
LEGS_TO_HOP = 1
LEGS_TO_WALK = 2
LEGS_TO_RUN = 2
WINGS_TO_FLY = 2
